version: '2'

services:
  moodle:
    container_name: moodle-3.2
    image: moodlefreak/moodle:latest
    links:
     - database
    ports:
     - "8080:80"
    environment:
      MOODLE_URL: 'http://localhost:8080'
      MOODLE_DIVERTALLEMAILSTO: 'debug@domain.com'
      DB_PORT_3306_TCP_ADDR: database
      DB_ENV_MYSQL_DATABASE: moodle
      DB_ENV_MYSQL_USER: moodle
      DB_ENV_MYSQL_PASSWORD: moodle
    volumes:
      - ".:/var/www/html/blocks/sample"